project_id = "cgnjxjstsbgwnpytqbqg"

[functions.convert-pi]
verify_jwt = false

[functions.request-withdrawal]
verify_jwt = false

[functions.credit-mining]
verify_jwt = false

[functions.mining-status]
verify_jwt = false

[functions.fedapay-webhook]
verify_jwt = false

[functions.fedapay-config]
verify_jwt = false
